@baseUrl = http://localhost:3000/api

#Auth

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "email11@mail.com",
  "password": "123@9976"
}

> {% client.global.set("authToken", response.body.accessToken); %}

### App AppTest

#@name RecadosTest
# GET All Recados
###
GET {{baseUrl}}/recados
    ?offset=0
    &limit=2
Authorization: Bearer {{authToken}}

#GET Recado
###
GET {{baseUrl}}/recados/1
Authorization: Bearer {{authToken}}

# POST create Recado
###
POST {{baseUrl}}/recados
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "paraId": 1,
  "texto": "Oi, tudo bem?"
}

###
PATCH {{baseUrl}}/recados/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "texto": "Oi, tudo bem mesmo né?"
}

###
DELETE {{baseUrl}}/recados/10
Authorization: Bearer {{authToken}}

```

#@name PessoaTest
# GET All Pessoas

###
GET {{baseUrl}}/pessoas
    ?offset=0
    &limit=2
Authorization: Bearer {{authToken}}

#GET Pessoa
###
GET {{baseUrl}}/pessoas/2
Authorization: Bearer {{authToken}}

# POST create Pessoa
###
POST {{baseUrl}}/pessoas
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "nome": "Fulano",
  "email": "email11a@mail.com",
  "password": "123@abc"
}

###
PATCH {{baseUrl}}/pessoas/9
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "nome": "Ciclano",
  "password": "123@9976"
}

###
DELETE {{baseUrl}}/pessoas/1
Authorization: Bearer {{authToken}}


```
