version: "3.8"

services:
  dcs-postgres:
    image: postgres:16.4-alpine
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres # Você pode adicionar um banco de dados padrão, se desejar
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Altere para um email de sua preferência
      PGADMIN_DEFAULT_PASSWORD: admin # Altere para uma senha de sua preferência
    ports:
      - 8080:80
    depends_on:
      - dcs-postgres

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/db
